---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db
  namespace: n8n
spec:
  encryptedData:
    PASSWORD: AgAYUAZGG9ogrXHmjC7JYAcEXttKkzf8NxPGj1vHBUTAnc2mRmvxaOhIdp6HTNfpUQIto8Pu9GvBa+nFSBTnNwW2WKTXlQSsntESLH7WMY8S8Txw5JbwPkeMcQ+SU0c2NgEp/iYrbQoAWwgkVc5n2gMGsmIW1jG1Vog7egoMZBsJwOhXLIey8OCCQMAnuwuFdXlFOq5QlYCHoQ5j5C/aU7gjmfmzNWj5gufGdEOjn097p0wSLPeWNL9KwUSdD5dkLDq6vi2MvDkNNiWqFzPu2g1/1pnnOGXAQ969tBug/3x9Yz/c4WFRj9nJhW7wQ6HIqv5Rlu6ALDphnfmx9dCLfHa7m2+f4vWCvYMFvFrhiS4V0QBkuyUd4LMSmoePJwX1XO8ewU+4YidYJlWbEedx7MaKuvn+Y2vNAj8qCamZC7VQ0fbLe+ciHFdGKg/N9lz/KdR9QL1fQUYD+6Zyopy1na0IU65RxXKyh3thw2UYr/WmSnxJn6krwE/xzXf9NnPUkZWQpRxrQTL+EAhLk4Ksl4V86Zq76eF8IcG/H6urREWFzMH4gFYo0yU9pXW8z77sfengRfencL8TMHpRnSbnbRv76dfO/HGNIXm7KpyyKcNC1xr5s1ViC8rhzeXb5GPoU7K6eXPlgsFxOuFF3neXf/2gRhuL+Yx9c4Ylw8ioPjtBbabGrFUJELmBO1VK1VKk0RMktsyr6dzaZgM=
  template:
    metadata:
      name: n8n-db
      namespace: n8n
