---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db
  namespace: n8n
spec:
  encryptedData:
    DATABASE_URL: AgAZBPf0lWnWKORtUMMUnU1nBQcq6MLLwIuYi8byn9worNuJLSwzjZ79rVV7QdxDEsgIs94kuXljDergHTqt8fwoPAhUPz0VgtCsT+rrnYsam68saDum7xypSdZcLDjBotrk+HcHKjKAX/LFQ5zm7bG+5DnoAwmIiuE9CYD+JRnx0nZhC1+SOoa0N4THpSfbSMPL2WpsVyeTagxKH7zojpG0ONUHrJwyJTgfYlJdWJf04sWJxU8WTILi3nucOjHkE/+/1qRGQmxDhgSDnSYQmzBxFi+bj9sEFbLKsIcVd2qvFHJJmphxsCf60NpUGgbifLHKH9XZPoJ1zopFnhRQivOWjTTfL+VYn8dZaJpqdB5KEyvu3DxF3UFyAxBO6HeA45B7qA8TGQdmvQNSAO4ItJC1W3TmUf/TqlOmWSHj/JfG7l7ZqpHkNg2XN5GBB9Vmx+HTt69aC2WB9j5IPIQ6XVOJMgkPf5cS66Z383jKi/6f3AfjoeHLh+IjXfxW+zDA4D0xI+kKgiPa/iGfUzCKuSgj8m/5L0g2FyCipekDnQvpN6RbFWYyXL0jnAYPZhjB4LHg1iWeq5NGrsHvFzygW+LM+yyDIohYxJO7R32jD8aOrUVj/MLHkYh3x4rAjvMgym4iqpOMEPzSFKDe1ZCr6LzIz2z6YmHfQi659XPWVz/64KOkGvsygI6dYkuYu7N7gQd8p3S3EU3UTaIQ2Z3a9duLjxT61Q0XtftiTnIP0LZhGyNI3w6RdN3vWqlFFnLYb/XFhrJXpVixMqlBklJXCkF+f3Ax0as+QQA=
  template:
    metadata:
      name: n8n-db
      namespace: n8n
