---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgAbAqDq5ZNDYnlNRAtVI0S7x7wSU4I9xs5S9Rci8jg0sO23o0I7C+znlTkmNQQuySqG2mR1kakj5HPojLXwbq3G9Z5fRrH6cdJa2ysSc1wxKRaV7xjKiHhYMHWe4X4osKcDewanOmazj61Y2xYx2TuNdgD6LDD9l6QV0v9l4TmJf2fRmR4forULZ7pY+9TQ4X14uF98NzKVRCX7AZObXqlYx1XU5t0kvFIi/NZPQDpUSGpfe2cubo22pAZQHGkK1dwfw4Gmw6+k70Z0vIGWzaczBc/+EYdxYfwblur3UNbDVRRmtcHYCgZfW24woKmmHJs6ZU+7tQPvlIV71elwk6cl70yswNxMz7CJ6JfNgxilJb0/4CHIQed4plBnVwbcafAyx9+tRYmZf4rLKU9Yo1BKWDHOnGXBtJ+igIzrnnPORrXS2i+0HT4uSTD5YtaRadpW9hV9/LxuqeKmaz6dL6ou9ZKPuMekBQhfNAyjJB+U/gGlq/Bl6HiqOiC/2dv8NoHcro8mwRdh/vp+o2fXUVcIX8aThfzU5OVm66DOOuDNFlcOLLsao5LvsM5REmXDDOOPSmogPFNLbdE6AyhaXNw/fJbzVPGvz0yJ/cF2IWkUeDhSNp8eZxmKNZwMUCHQ7mJMzU/kdAOtA1X2Iq2G9BjIACggMXMuoTwHJyo6L1sVkPABrMH0hgr1CP0fpozEWJC1QvS859pqZIShSHW7+vsXBHs1cMuUyC7A26IWUAWmAvUVQOYEouj7k04SaQ1MK3UQG2Br1z/LJU9kS35znT/dQAd9G77LZfQ=
  template:
    metadata:
      name: n8n-db
      namespace: default
