apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hound
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HPerssn/homelab
    targetRevision: HEAD
    path: apps/hound
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
