ports:
  web:
    port: 80
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    exposedPort: 443
    protocol: TCP

deployment:
  hostnetwork: true

tolerations:
  - key: "llm"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-control

additionalArguments:
  - "--providers.kubernetesgateway=true"

providers:
  kubernetesIngress:
    enabled: true

metrics:
  prometheus:
    enabled: true
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

ports:
  metrics:
    port: 9100
    expose: false
    exposedPort: 9100
    protocol: TCP

additionalArguments:
  - "--metrics.prometheus=true"
