server:
  ingress:
    enabled: true  
    ingressClassName: traefik
    hosts:
      - argocd.lab.hpersson.com
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.lab.hpersson.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
  
  extraArgs:
    - --insecure
