admin:
  existingSecret: "pihole-password"
  passwordKey: "password"

timezone: "Europe/Stockholm"

DNS1: "1.1.1.1"
DNS2: "1.0.0.1"

serviceDns:
  type: LoadBalancer

serviceWeb:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - pihole.lab.hpersson.com
  tls:
    - secretName: pihole-tls
      hosts:
        - pihole.lab.hpersson.com

persistentVolumeClaim:
  enabled: true
  storageClass: "longhorn"
  accessModes:
    - ReadWriteOnce
  size: "1Gi"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
